# Generated by Django 4.2.1 on 2023-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lesson_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
