# Generated by Django 4.2.1 on 2023-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_lessoncompleted_user_lessoncompleted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(default='https://opik.fyysika.ee/media/img/book/id-71.v-65iin.w-150.h-207.jpg'),
            preserve_default=False,
        ),
    ]
