# Generated by Django 4.2.1 on 2023-05-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompleted',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
        ),
    ]
