# Generated by Django 4.2.1 on 2023-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lesson_onlyforadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonNumber',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
