# Generated by Django 4.2.1 on 2023-05-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_lesson_lessonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kasutajad',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.TextField(blank=True, default='https://previews.123rf.com/images/tupungato/tupungato1612/tupungato161200137/69249841-physics-lesson-hand-written-law-of-physics-equations-set-science-vector-illustration.jpg'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
    ]
