# Generated by Django 4.2.1 on 2023-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_lessoncompleted_user_lessoncompleted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_max',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_min',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
