# Generated by Django 4.2.1 on 2023-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constant',
            field=models.FloatField(default=1.0),
        ),
    ]
