# Generated by Django 4.2.1 on 2023-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_question_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='constant',
            field=models.CharField(default='random_data', max_length=255),
        ),
    ]
