# Generated by Django 4.2.1 on 2023-06-04 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_course_only_for_admin_alter_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kasutajad',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
